export const CATEGORIES = [
  { slug: "electronics", label: "Electronics", icon: "Cpu", type: "goods" },
  { slug: "vehicles", label: "Vehicles", icon: "Car", type: "goods" },
  { slug: "fashion", label: "Fashion", icon: "Shirt", type: "goods" },
  { slug: "home", label: "Home & Furniture", icon: "Sofa", type: "goods" },
  { slug: "phones", label: "Phones & Tablets", icon: "Smartphone", type: "goods" },
  { slug: "property", label: "Property", icon: "Building2", type: "goods" },
  { slug: "appliances", label: "Home Appliances", icon: "Refrigerator", type: "goods" },
  { slug: "beauty", label: "Beauty & Personal Care", icon: "Sparkles", type: "goods" },
  { slug: "baby", label: "Baby & Kids", icon: "Baby", type: "goods" },
  { slug: "food", label: "Food & Agriculture", icon: "Apple", type: "goods" },
  { slug: "sports", label: "Sports & Outdoors", icon: "Dumbbell", type: "goods" },
  { slug: "books", label: "Books & Media", icon: "Book", type: "goods" },
  { slug: "gaming", label: "Gaming", icon: "Gamepad2", type: "goods" },
  { slug: "pets", label: "Pets & Animals", icon: "PawPrint", type: "goods" },
  { slug: "industrial", label: "Industrial & Tools", icon: "HardHat", type: "goods" },
  { slug: "art", label: "Art & Collectibles", icon: "Palette", type: "goods" },
  { slug: "health", label: "Health & Wellness", icon: "HeartPulse", type: "goods" },
  { slug: "office", label: "Office Supplies", icon: "Briefcase", type: "goods" },
  { slug: "plumbing", label: "Plumbing", icon: "Wrench", type: "service" },
  { slug: "tutoring", label: "Tutoring", icon: "BookOpen", type: "service" },
  { slug: "design", label: "Design & Creative", icon: "Palette", type: "service" },
  { slug: "cleaning", label: "Cleaning", icon: "Sparkles", type: "service" },
  { slug: "tech-services", label: "Tech Services", icon: "Code2", type: "service" },
  { slug: "events", label: "Event Planning", icon: "PartyPopper", type: "service" },
  { slug: "photography", label: "Photography & Video", icon: "Camera", type: "service" },
  { slug: "beauty-services", label: "Beauty & Spa", icon: "Scissors", type: "service" },
  { slug: "legal", label: "Legal Services", icon: "Scale", type: "service" },
  { slug: "accounting", label: "Accounting & Tax", icon: "Calculator", type: "service" },
  { slug: "fitness", label: "Fitness & Coaching", icon: "Dumbbell", type: "service" },
  { slug: "transport", label: "Transport & Logistics", icon: "Truck", type: "service" },
  { slug: "electrical", label: "Electrical", icon: "Zap", type: "service" },
  { slug: "carpentry", label: "Carpentry", icon: "Hammer", type: "service" },
  { slug: "auto-repair", label: "Auto Repair", icon: "Car", type: "service" },
  { slug: "tailoring", label: "Tailoring & Fashion", icon: "Shirt", type: "service" },
  { slug: "catering", label: "Catering & Chef", icon: "ChefHat", type: "service" },
  { slug: "real-estate", label: "Real Estate Agent", icon: "Home", type: "service" },
  { slug: "marketing", label: "Marketing & PR", icon: "Megaphone", type: "service" },
  { slug: "translation", label: "Translation & Writing", icon: "Languages", type: "service" },
  { slug: "healthcare", label: "Health & Medical", icon: "Stethoscope", type: "service" },
] as const;

export const LOCATIONS = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT - Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

export const formatNaira = (n: number | null | undefined) =>
  n == null
    ? "—"
    : new Intl.NumberFormat("en-NG", {
        style: "currency",
        currency: "NGN",
        maximumFractionDigits: 0,
      }).format(n);
