/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostAdRouteImport } from './routes/post-ad'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as ArtisansIndexRouteImport } from './routes/artisans/index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as MessagesChatIdRouteImport } from './routes/messages.$chatId'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as ArtisanCreateRouteImport } from './routes/artisan/create'

const PostAdRoute = PostAdRouteImport.update({
  id: '/post-ad',
  path: '/post-ad',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MessagesRoute,
} as any)
const ArtisansIndexRoute = ArtisansIndexRouteImport.update({
  id: '/artisans/',
  path: '/artisans/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesChatIdRoute = MessagesChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => MessagesRoute,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanCreateRoute = ArtisanCreateRouteImport.update({
  id: '/artisan/create',
  path: '/artisan/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/messages': typeof MessagesRouteWithChildren
  '/post-ad': typeof PostAdRoute
  '/artisan/create': typeof ArtisanCreateRoute
  '/listing/$id': typeof ListingIdRoute
  '/messages/$chatId': typeof MessagesChatIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/artisans/': typeof ArtisansIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/post-ad': typeof PostAdRoute
  '/artisan/create': typeof ArtisanCreateRoute
  '/listing/$id': typeof ListingIdRoute
  '/messages/$chatId': typeof MessagesChatIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/artisans': typeof ArtisansIndexRoute
  '/messages': typeof MessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/messages': typeof MessagesRouteWithChildren
  '/post-ad': typeof PostAdRoute
  '/artisan/create': typeof ArtisanCreateRoute
  '/listing/$id': typeof ListingIdRoute
  '/messages/$chatId': typeof MessagesChatIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/artisans/': typeof ArtisansIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/messages'
    | '/post-ad'
    | '/artisan/create'
    | '/listing/$id'
    | '/messages/$chatId'
    | '/shop/$slug'
    | '/artisans/'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/post-ad'
    | '/artisan/create'
    | '/listing/$id'
    | '/messages/$chatId'
    | '/shop/$slug'
    | '/artisans'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/messages'
    | '/post-ad'
    | '/artisan/create'
    | '/listing/$id'
    | '/messages/$chatId'
    | '/shop/$slug'
    | '/artisans/'
    | '/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  PostAdRoute: typeof PostAdRoute
  ArtisanCreateRoute: typeof ArtisanCreateRoute
  ListingIdRoute: typeof ListingIdRoute
  ShopSlugRoute: typeof ShopSlugRoute
  ArtisansIndexRoute: typeof ArtisansIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/post-ad': {
      id: '/post-ad'
      path: '/post-ad'
      fullPath: '/post-ad'
      preLoaderRoute: typeof PostAdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/artisans/': {
      id: '/artisans/'
      path: '/artisans'
      fullPath: '/artisans/'
      preLoaderRoute: typeof ArtisansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$chatId': {
      id: '/messages/$chatId'
      path: '/$chatId'
      fullPath: '/messages/$chatId'
      preLoaderRoute: typeof MessagesChatIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/create': {
      id: '/artisan/create'
      path: '/artisan/create'
      fullPath: '/artisan/create'
      preLoaderRoute: typeof ArtisanCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MessagesRouteChildren {
  MessagesChatIdRoute: typeof MessagesChatIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesChatIdRoute: MessagesChatIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  MessagesRoute: MessagesRouteWithChildren,
  PostAdRoute: PostAdRoute,
  ArtisanCreateRoute: ArtisanCreateRoute,
  ListingIdRoute: ListingIdRoute,
  ShopSlugRoute: ShopSlugRoute,
  ArtisansIndexRoute: ArtisansIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
