/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArtisanTermsRouteImport } from './routes/artisan-terms'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BillingTermsRouteImport } from './routes/billing-terms'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PostAdRouteImport } from './routes/post-ad'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SellerTermsRouteImport } from './routes/seller-terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as WaitListRouteImport } from './routes/wait-list'
import { Route as AdminDirectoryRouteImport } from './routes/admin_.directory'
import { Route as AdminWaitlistRouteImport } from './routes/admin_.waitlist'
import { Route as ArtisanCreateRouteImport } from './routes/artisan/create'
import { Route as ArtisanEditRouteImport } from './routes/artisan/edit'
import { Route as ArtisansIndexRouteImport } from './routes/artisans/index'
import { Route as ArtisansIdRouteImport } from './routes/artisans.$id'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as MessagesChatIdRouteImport } from './routes/messages.$chatId'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanTermsRoute = ArtisanTermsRouteImport.update({
  id: '/artisan-terms',
  path: '/artisan-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingTermsRoute = BillingTermsRouteImport.update({
  id: '/billing-terms',
  path: '/billing-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PostAdRoute = PostAdRouteImport.update({
  id: '/post-ad',
  path: '/post-ad',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerTermsRoute = SellerTermsRouteImport.update({
  id: '/seller-terms',
  path: '/seller-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitListRoute = WaitListRouteImport.update({
  id: '/wait-list',
  path: '/wait-list',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDirectoryRoute = AdminDirectoryRouteImport.update({
  id: '/admin_/directory',
  path: '/admin/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWaitlistRoute = AdminWaitlistRouteImport.update({
  id: '/admin_/waitlist',
  path: '/admin/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanCreateRoute = ArtisanCreateRouteImport.update({
  id: '/artisan/create',
  path: '/artisan/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanEditRoute = ArtisanEditRouteImport.update({
  id: '/artisan/edit',
  path: '/artisan/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisansIndexRoute = ArtisansIndexRouteImport.update({
  id: '/artisans/',
  path: '/artisans/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisansIdRoute = ArtisansIdRouteImport.update({
  id: '/artisans/$id',
  path: '/artisans/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MessagesRoute,
} as any)
const MessagesChatIdRoute = MessagesChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => MessagesRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/admin': typeof AdminRoute
  '/artisan-terms': typeof ArtisanTermsRoute
  '/auth': typeof AuthRoute
  '/billing-terms': typeof BillingTermsRoute
  '/complaints': typeof ComplaintsRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/post-ad': typeof PostAdRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seller-terms': typeof SellerTermsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wait-list': typeof WaitListRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/artisan/create': typeof ArtisanCreateRoute
  '/artisan/edit': typeof ArtisanEditRoute
  '/artisans/$id': typeof ArtisansIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/messages/$chatId': typeof MessagesChatIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/artisans/': typeof ArtisansIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/admin': typeof AdminRoute
  '/artisan-terms': typeof ArtisanTermsRoute
  '/auth': typeof AuthRoute
  '/billing-terms': typeof BillingTermsRoute
  '/complaints': typeof ComplaintsRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/post-ad': typeof PostAdRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seller-terms': typeof SellerTermsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wait-list': typeof WaitListRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/artisan/create': typeof ArtisanCreateRoute
  '/artisan/edit': typeof ArtisanEditRoute
  '/artisans/$id': typeof ArtisansIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/messages/$chatId': typeof MessagesChatIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/artisans': typeof ArtisansIndexRoute
  '/messages': typeof MessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/admin': typeof AdminRoute
  '/artisan-terms': typeof ArtisanTermsRoute
  '/auth': typeof AuthRoute
  '/billing-terms': typeof BillingTermsRoute
  '/complaints': typeof ComplaintsRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/post-ad': typeof PostAdRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seller-terms': typeof SellerTermsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wait-list': typeof WaitListRoute
  '/admin_/directory': typeof AdminDirectoryRoute
  '/admin_/waitlist': typeof AdminWaitlistRoute
  '/artisan/create': typeof ArtisanCreateRoute
  '/artisan/edit': typeof ArtisanEditRoute
  '/artisans/$id': typeof ArtisansIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/messages/$chatId': typeof MessagesChatIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/artisans/': typeof ArtisansIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceptable-use'
    | '/admin'
    | '/artisan-terms'
    | '/auth'
    | '/billing-terms'
    | '/complaints'
    | '/cookies'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/post-ad'
    | '/privacy'
    | '/reset-password'
    | '/seller-terms'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/wait-list'
    | '/admin/directory'
    | '/admin/waitlist'
    | '/artisan/create'
    | '/artisan/edit'
    | '/artisans/$id'
    | '/listing/$id'
    | '/messages/$chatId'
    | '/shop/$slug'
    | '/artisans/'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceptable-use'
    | '/admin'
    | '/artisan-terms'
    | '/auth'
    | '/billing-terms'
    | '/complaints'
    | '/cookies'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/post-ad'
    | '/privacy'
    | '/reset-password'
    | '/seller-terms'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/wait-list'
    | '/admin/directory'
    | '/admin/waitlist'
    | '/artisan/create'
    | '/artisan/edit'
    | '/artisans/$id'
    | '/listing/$id'
    | '/messages/$chatId'
    | '/shop/$slug'
    | '/artisans'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/acceptable-use'
    | '/admin'
    | '/artisan-terms'
    | '/auth'
    | '/billing-terms'
    | '/complaints'
    | '/cookies'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/post-ad'
    | '/privacy'
    | '/reset-password'
    | '/seller-terms'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/wait-list'
    | '/admin_/directory'
    | '/admin_/waitlist'
    | '/artisan/create'
    | '/artisan/edit'
    | '/artisans/$id'
    | '/listing/$id'
    | '/messages/$chatId'
    | '/shop/$slug'
    | '/artisans/'
    | '/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptableUseRoute: typeof AcceptableUseRoute
  AdminRoute: typeof AdminRoute
  ArtisanTermsRoute: typeof ArtisanTermsRoute
  AuthRoute: typeof AuthRoute
  BillingTermsRoute: typeof BillingTermsRoute
  ComplaintsRoute: typeof ComplaintsRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  PostAdRoute: typeof PostAdRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SellerTermsRoute: typeof SellerTermsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WaitListRoute: typeof WaitListRoute
  AdminDirectoryRoute: typeof AdminDirectoryRoute
  AdminWaitlistRoute: typeof AdminWaitlistRoute
  ArtisanCreateRoute: typeof ArtisanCreateRoute
  ArtisanEditRoute: typeof ArtisanEditRoute
  ArtisansIdRoute: typeof ArtisansIdRoute
  ListingIdRoute: typeof ListingIdRoute
  ShopSlugRoute: typeof ShopSlugRoute
  ArtisansIndexRoute: typeof ArtisansIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan-terms': {
      id: '/artisan-terms'
      path: '/artisan-terms'
      fullPath: '/artisan-terms'
      preLoaderRoute: typeof ArtisanTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing-terms': {
      id: '/billing-terms'
      path: '/billing-terms'
      fullPath: '/billing-terms'
      preLoaderRoute: typeof BillingTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-ad': {
      id: '/post-ad'
      path: '/post-ad'
      fullPath: '/post-ad'
      preLoaderRoute: typeof PostAdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-terms': {
      id: '/seller-terms'
      path: '/seller-terms'
      fullPath: '/seller-terms'
      preLoaderRoute: typeof SellerTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wait-list': {
      id: '/wait-list'
      path: '/wait-list'
      fullPath: '/wait-list'
      preLoaderRoute: typeof WaitListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/directory': {
      id: '/admin_/directory'
      path: '/admin/directory'
      fullPath: '/admin/directory'
      preLoaderRoute: typeof AdminDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/waitlist': {
      id: '/admin_/waitlist'
      path: '/admin/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AdminWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/create': {
      id: '/artisan/create'
      path: '/artisan/create'
      fullPath: '/artisan/create'
      preLoaderRoute: typeof ArtisanCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/edit': {
      id: '/artisan/edit'
      path: '/artisan/edit'
      fullPath: '/artisan/edit'
      preLoaderRoute: typeof ArtisanEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisans/': {
      id: '/artisans/'
      path: '/artisans'
      fullPath: '/artisans/'
      preLoaderRoute: typeof ArtisansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisans/$id': {
      id: '/artisans/$id'
      path: '/artisans/$id'
      fullPath: '/artisans/$id'
      preLoaderRoute: typeof ArtisansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/messages/$chatId': {
      id: '/messages/$chatId'
      path: '/$chatId'
      fullPath: '/messages/$chatId'
      preLoaderRoute: typeof MessagesChatIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MessagesRouteChildren {
  MessagesChatIdRoute: typeof MessagesChatIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesChatIdRoute: MessagesChatIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptableUseRoute: AcceptableUseRoute,
  AdminRoute: AdminRoute,
  ArtisanTermsRoute: ArtisanTermsRoute,
  AuthRoute: AuthRoute,
  BillingTermsRoute: BillingTermsRoute,
  ComplaintsRoute: ComplaintsRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRouteWithChildren,
  PostAdRoute: PostAdRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SellerTermsRoute: SellerTermsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WaitListRoute: WaitListRoute,
  AdminDirectoryRoute: AdminDirectoryRoute,
  AdminWaitlistRoute: AdminWaitlistRoute,
  ArtisanCreateRoute: ArtisanCreateRoute,
  ArtisanEditRoute: ArtisanEditRoute,
  ArtisansIdRoute: ArtisansIdRoute,
  ListingIdRoute: ListingIdRoute,
  ShopSlugRoute: ShopSlugRoute,
  ArtisansIndexRoute: ArtisansIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
