-- Seed Nigerian states and common local government areas for the location dropdowns.
-- This migration is idempotent and safe to run more than once.

CREATE TABLE IF NOT EXISTS public.states (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.lgas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  state_id uuid REFERENCES public.states(id),
  created_at timestamptz DEFAULT now()
);

GRANT SELECT ON public.states TO anon, authenticated;
GRANT SELECT ON public.lgas TO anon, authenticated;
GRANT ALL ON public.states, public.lgas TO service_role;

ALTER TABLE public.states ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lgas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "states public read" ON public.states;
CREATE POLICY "states public read" ON public.states FOR SELECT USING (true);
DROP POLICY IF EXISTS "lgas public read" ON public.lgas;
CREATE POLICY "lgas public read" ON public.lgas FOR SELECT USING (true);

INSERT INTO public.states (name)
VALUES
  ('Abia'),
  ('Adamawa'),
  ('Akwa Ibom'),
  ('Anambra'),
  ('Bauchi'),
  ('Bayelsa'),
  ('Benue'),
  ('Borno'),
  ('Cross River'),
  ('Delta'),
  ('Ebonyi'),
  ('Edo'),
  ('Ekiti'),
  ('Enugu'),
  ('FCT - Abuja'),
  ('Gombe'),
  ('Imo'),
  ('Jigawa'),
  ('Kaduna'),
  ('Kano'),
  ('Katsina'),
  ('Kebbi'),
  ('Kogi'),
  ('Kwara'),
  ('Lagos'),
  ('Nasarawa'),
  ('Niger'),
  ('Ogun'),
  ('Ondo'),
  ('Osun'),
  ('Oyo'),
  ('Plateau'),
  ('Rivers'),
  ('Sokoto'),
  ('Taraba'),
  ('Yobe'),
  ('Zamfara')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.lgas (name, state_id)
SELECT v.name, s.id
FROM (
  VALUES
    ('Aba North', 'Abia'),
    ('Aba South', 'Abia'),
    ('Umuahia North', 'Abia'),
    ('Umuahia South', 'Abia'),
    ('Isiala Ngwa North', 'Abia'),
    ('Yola North', 'Adamawa'),
    ('Yola South', 'Adamawa'),
    ('Mubi North', 'Adamawa'),
    ('Mubi South', 'Adamawa'),
    ('Numan', 'Adamawa'),
    ('Uyo', 'Akwa Ibom'),
    ('Ikot Ekpene', 'Akwa Ibom'),
    ('Etinan', 'Akwa Ibom'),
    ('Eket', 'Akwa Ibom'),
    ('Oron', 'Akwa Ibom'),
    ('Awka South', 'Anambra'),
    ('Awka North', 'Anambra'),
    ('Onitsha North', 'Anambra'),
    ('Onitsha South', 'Anambra'),
    ('Nnewi North', 'Anambra'),
    ('Bauchi', 'Bauchi'),
    ('Alkaleri', 'Bauchi'),
    ('Toro', 'Bauchi'),
    ('Ningi', 'Bauchi'),
    ('Jamaare', 'Bauchi'),
    ('Yenagoa', 'Bayelsa'),
    ('Sagbama', 'Bayelsa'),
    ('Ogbia', 'Bayelsa'),
    ('Ekeremor', 'Bayelsa'),
    ('Brass', 'Bayelsa'),
    ('Makurdi', 'Benue'),
    ('Gboko', 'Benue'),
    ('Otukpo', 'Benue'),
    ('Katsina-Ala', 'Benue'),
    ('Kwande', 'Benue'),
    ('Maiduguri', 'Borno'),
    ('Jere', 'Borno'),
    ('Bama', 'Borno'),
    ('Konduga', 'Borno'),
    ('Dikwa', 'Borno'),
    ('Calabar Municipal', 'Cross River'),
    ('Calabar South', 'Cross River'),
    ('Akpabuyo', 'Cross River'),
    ('Odukpani', 'Cross River'),
    ('Obubra', 'Cross River'),
    ('Warri South', 'Delta'),
    ('Warri North', 'Delta'),
    ('Udu', 'Delta'),
    ('Ughelli North', 'Delta'),
    ('Sapele', 'Delta'),
    ('Abakaliki', 'Ebonyi'),
    ('Afikpo North', 'Ebonyi'),
    ('Afikpo South', 'Ebonyi'),
    ('Ezza North', 'Ebonyi'),
    ('Ezza South', 'Ebonyi'),
    ('Benin City', 'Edo'),
    ('Oredo', 'Edo'),
    ('Egor', 'Edo'),
    ('Ikpoba Okha', 'Edo'),
    ('Uhunmwonde', 'Edo'),
    ('Ado Ekiti', 'Ekiti'),
    ('Ikere', 'Ekiti'),
    ('Ikole', 'Ekiti'),
    ('Oye', 'Ekiti'),
    ('Efon', 'Ekiti'),
    ('Enugu East', 'Enugu'),
    ('Enugu North', 'Enugu'),
    ('Enugu South', 'Enugu'),
    ('Nkanu East', 'Enugu'),
    ('Nsukka', 'Enugu'),
    ('Abuja Municipal', 'FCT - Abuja'),
    ('Bwari', 'FCT - Abuja'),
    ('Gwagwalada', 'FCT - Abuja'),
    ('Kuje', 'FCT - Abuja'),
    ('Kwali', 'FCT - Abuja'),
    ('Gombe', 'Gombe'),
    ('Akko', 'Gombe'),
    ('Yamaltu Deba', 'Gombe'),
    ('Kwami', 'Gombe'),
    ('Balanga', 'Gombe'),
    ('Owerri Municipal', 'Imo'),
    ('Owerri North', 'Imo'),
    ('Owerri West', 'Imo'),
    ('Orlu', 'Imo'),
    ('Okigwe', 'Imo'),
    ('Dutse', 'Jigawa'),
    ('Jahun', 'Jigawa'),
    ('Gumel', 'Jigawa'),
    ('Hadejia', 'Jigawa'),
    ('Kazaure', 'Jigawa'),
    ('Kaduna North', 'Kaduna'),
    ('Kaduna South', 'Kaduna'),
    ('Zaria', 'Kaduna'),
    ('Chikun', 'Kaduna'),
    ('Giwa', 'Kaduna'),
    ('Kano Municipal', 'Kano'),
    ('Nassarawa', 'Kano'),
    ('Dala', 'Kano'),
    ('Fagge', 'Kano'),
    ('Ungogo', 'Kano'),
    ('Katsina', 'Katsina'),
    ('Daura', 'Katsina'),
    ('Funtua', 'Katsina'),
    ('Kankia', 'Katsina'),
    ('Malumfashi', 'Katsina'),
    ('Birnin Kebbi', 'Kebbi'),
    ('Argungu', 'Kebbi'),
    ('Yauri', 'Kebbi'),
    ('Zuru', 'Kebbi'),
    ('Jega', 'Kebbi'),
    ('Lokoja', 'Kogi'),
    ('Okene', 'Kogi'),
    ('Kabba/Bunu', 'Kogi'),
    ('Idah', 'Kogi'),
    ('Ankpa', 'Kogi'),
    ('Ilorin East', 'Kwara'),
    ('Ilorin West', 'Kwara'),
    ('Ilorin South', 'Kwara'),
    ('Offa', 'Kwara'),
    ('Asa', 'Kwara'),
    ('Ikeja', 'Lagos'),
    ('Surulere', 'Lagos'),
    ('Lagos Island', 'Lagos'),
    ('Eti Osa', 'Lagos'),
    ('Alimosho', 'Lagos'),
    ('Lafia', 'Nasarawa'),
    ('Keffi', 'Nasarawa'),
    ('Akwanga', 'Nasarawa'),
    ('Karu', 'Nasarawa'),
    ('Nasarawa', 'Nasarawa'),
    ('Minna', 'Niger'),
    ('Bida', 'Niger'),
    ('Kontagora', 'Niger'),
    ('Suleja', 'Niger'),
    ('Mokwa', 'Niger'),
    ('Abeokuta North', 'Ogun'),
    ('Abeokuta South', 'Ogun'),
    ('Ifo', 'Ogun'),
    ('Odeda', 'Ogun'),
    ('Sagamu', 'Ogun'),
    ('Akure South', 'Ondo'),
    ('Akure North', 'Ondo'),
    ('Ondo East', 'Ondo'),
    ('Ondo West', 'Ondo'),
    ('Owo', 'Ondo'),
    ('Osogbo', 'Osun'),
    ('Iwo', 'Osun'),
    ('Ife East', 'Osun'),
    ('Ife Central', 'Osun'),
    ('Ejigbo', 'Osun'),
    ('Ibadan North', 'Oyo'),
    ('Ibadan South East', 'Oyo'),
    ('Ibadan North East', 'Oyo'),
    ('Ogbomosho North', 'Oyo'),
    ('Oyo East', 'Oyo'),
    ('Jos North', 'Plateau'),
    ('Jos South', 'Plateau'),
    ('Barkin Ladi', 'Plateau'),
    ('Riyom', 'Plateau'),
    ('Mangu', 'Plateau'),
    ('Port Harcourt', 'Rivers'),
    ('Obio/Akpor', 'Rivers'),
    ('Ikwerre', 'Rivers'),
    ('Eleme', 'Rivers'),
    ('Okrika', 'Rivers'),
    ('Sokoto North', 'Sokoto'),
    ('Sokoto South', 'Sokoto'),
    ('Wamakko', 'Sokoto'),
    ('Tambuwal', 'Sokoto'),
    ('Kebbe', 'Sokoto'),
    ('Jalingo', 'Taraba'),
    ('Wukari', 'Taraba'),
    ('Lau', 'Taraba'),
    ('Gassol', 'Taraba'),
    ('Ibi', 'Taraba'),
    ('Damaturu', 'Yobe'),
    ('Potiskum', 'Yobe'),
    ('Nguru', 'Yobe'),
    ('Geidam', 'Yobe'),
    ('Gashua', 'Yobe'),
    ('Gusau', 'Zamfara'),
    ('Kaura Namoda', 'Zamfara'),
    ('Maradun', 'Zamfara'),
    ('Talata Mafara', 'Zamfara'),
    ('Bakura', 'Zamfara')
) AS v(name, state_name)
JOIN public.states AS s ON s.name = v.state_name
WHERE NOT EXISTS (
  SELECT 1
  FROM public.lgas l
  WHERE l.name = v.name AND l.state_id = s.id
);
